- name: Ensure there is a system user named agama-client
  ansible.builtin.user:
   name: agama-client
   state: present

- name: Install fping
  ansible.builtin.apt:
    name: fping
    state: present

- name: Copy agama-client script 
  ansible.builtin.template:
    src: ../templates/agama-client
    dest: /usr/local/bin/agama-client
    mode: '0755'

- name: Configure service agama-client
  ansible.builtin.template:
    src: agama-client.service.j2
    dest: /etc/systemd/system/agama-client.service
  notify: daemon-reload

- name: Ensure /etc/agama-client directory is present
  ansible.builtin.file:
    path: /etc/agama-client
    state: directory

- name: Copy agama-client script 
  ansible.builtin.template:
    src: agama-client.conf.j2
    dest: /etc/agama-client/agama-client.conf
