- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy nginx configuration
  ansible.builtin.copy:
    src: default
    dest: /etc/nginx/sites-enabled/default
  notify: Restart nginx

- name: nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true