- name: Install nginx
  ansible.builtin.apt:
    name: 
      - nginx
      - prometheus-nginx-exporter
    state: present

- name: Copy nginx configuration
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: 
      - Restart nginx

- meta: flush_handlers

- name: Ensure nginx and exporter are enable and running
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - nginx
    - prometheus-nginx-exporter