- name: download influxdb
  ansible.builtin.get_url:
    url: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
    dest: /tmp/influxdb_1.8.10_amd64.deb

- name: add InfluxDB repository key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key

- name: Add InfluxDB APT repository
  apt_repository:
    repo: deb https://repos.influxdata.com/debian stable main

- name: install influxdb
  ansible.builtin.apt:
    deb: /tmp/influxdb_1.8.10_amd64.deb
    state: present

- name: Change influxdb conf file
  ansible.builtin.template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify: Restart influxdb

- name: Ensure influxdb is enable and running
  systemd:
    name: influxdb
    enabled: yes
    state: started

- name: install telegraf
  ansible.builtin.apt:
    name: telegraf
    state: present

- name: Create telegraf.conf
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf

- name: Ensure telegraf is enable and running
  systemd:
    name: telegraf
    enabled: yes
    state: started