- name: Initial setup
  hosts: all
  gather_facts: true
  roles:
    - init
  tags:
    - init
    # - always

- name: DNS server
  gather_facts: true
  hosts: dns_servers
  roles:
    - bind
  tags: 
    - b

- name: Resolver
  gather_facts: true
  hosts: all
  roles:
    - resolver
  tags: 
    - b
    - r

- name: Database server
  gather_facts: true
  hosts: db_servers
  roles:
    - mysql
  tags: 
    - db
    - mx

- name: Web server
  gather_facts: true
  hosts: web_servers
  roles:
    - docker
    - agama
    - nginx
  tags: 
    - w
    - mx

- name: Agama client server
  hosts: agama_client_servers
  roles:
    - agama_client
  tags: 
    - c

- name: prometheus
  gather_facts: true
  hosts: prometheus
  roles:
    - prometheus
    - nginx
  tags: 
    - p

- name: grafana
  hosts: grafana
  roles:
    - docker
    - grafana
    - nginx
  tags: 
    - g

- name: influxdb
  hosts: influxdb
  roles:
    - influxdb
  tags: 
    - i

- name: keepalived
  gather_facts: true
  hosts: keepalived
  roles:
    - keepalived
  tags: 
    - k

- name: haproxy
  gather_facts: true
  hosts: haproxy
  roles:
    - haproxy
  tags: 
    - h