- name: Initial setup
  hosts: all
  gather_facts: true
  roles:
    - init

- name: DNS server
  hosts: dns_servers
  roles:
    - bind
  tags: 
    - b

- name: Resolver
  hosts: all
  roles:
    - resolver
  tags: 
    - b

- name: Database server
  hosts: db_servers
  roles:
    - mysql

- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
