- name: Initial setup
  hosts: all
  gather_facts: true
  roles:
    - init
  tags:
    - init

- name: DNS server
  hosts: dns_servers
  roles:
    - bind
  tags: 
    - b

- name: Resolver
  hosts: all
  roles:
    - resolver
  tags: 
    - b

- name: Database server
  hosts: db_servers
  roles:
    - mysql
  tags: 
    - db

- name: Web server
  hosts: web_servers
  roles:
    - agama
    - uwsgi
    - nginx
  tags: 
    - w

- name: Agama client server
  hosts: agama_client_servers
  roles:
    - agama_client
  tags: 
    - c

- name: prometheus
  hosts: prometheus
  roles:
    - prometheus
    - nginx
  tags: 
    - p

- name: grafana
  hosts: grafana
  roles:
    - grafana
    - nginx
  tags: 
    - g

- name: influxdb
  hosts: influxdb
  roles:
    - influxdb
  tags: 
    - i