{
 "title": "mysql",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MySQL 1 id",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{job=\"mysql\", instance=\"manuniia-1:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL 2 id",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id{job=\"mysql\", instance=\"manuniia-2:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read only status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only{job=\"mysql\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MySQL replication threads",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "slave_sql_running",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}