- name: Ensure there is a system user named agama
  ansible.builtin.user:
   name: agama
   state: present
    
- name: Ensure /opt/agama directory is present and owned by agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    group: agama
    mode: '0755'
  
- name: Install application dependencies
  ansible.builtin.apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql

- name: Download and install the AGAMA application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py 
    owner: agama
    group: agama

