- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted

- name: rndc reload
  ansible.builtin.command: rndc reload

- name: daemon-reload
  systemd:
    daemon_reload: true
