- name: Ensure there is a system user named agama
  ansible.builtin.user:
   name: agama
   state: present
    
- name: Ensure /opt/agama directory is present and owned by agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama
    group: agama
    mode: '0755'
  
- name: Install application dependencies
  ansible.builtin.apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql

- name: Download and install the AGAMA application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama/agama.py 
    owner: agama
    group: agama

- name: Ensure there is a system user named agama-client
  ansible.builtin.user:
   name: agama-client
   state: present

- name: Copy agama-client script 
  ansible.builtin.template:
    src: ../templates/agama-client
    dest: /usr/local/bin/agama-client

- name: Configure service agama-client
  ansible.builtin.template:
    src: agama-client.service.j2
    dest: /etc/systemd/system/agama-client.service
  notify: daemon-reload

- name: Ensure /etc/agama-client directory is present
  ansible.builtin.file:
    path: /etc/agama-client
    state: directory

- name: Copy agama-client script 
  ansible.builtin.template:
    src: agama-client.conf.j2
    dest: /etc/agama-client/agama-client.conf
