- name: Ensure /opt/agama directory is present
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Download Dockerfile and AGAMA applicationc
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}"
    dest: "/opt/agama/{{ item }}"
  loop:
    - agama.py
    - Dockerfile

- name: Build Docker image for agama
  community.docker.docker_image:
    name: agama
    build:
      path: /opt/agama
    source: build

- name: Create agama container
  community.docker.docker_container:
    name: agama
    image: agama
    published_ports: "{{ agama_port }}:8000"
    env: 
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    state: started
    restart_policy: always
