- name: Ensure /opt/agama directory is present
  ansible.builtin.file:
    path: /opt/agama
    state: directory

- name: Download Dockerfile and AGAMA applicationc
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/hudolejev/agama/master/{{ item }}"
    dest: "/opt/agama/{{ item }}"
  loop:
    - agama.py
    - Dockerfile

- name: Build Docker image for agama
  community.docker.docker_image:
    name: agama
    build:
      path: /opt/agama
    source: build

- name: Create agama container
  community.docker.docker_container:
    name: "agama{{ item }}"
    image: agama
    published_ports: "800{{ item }}:8000"
    env: 
      AGAMA_DATABASE_URI: "mysql+pymysql://{{ mysql_user }}:{{ mysql_password }}@{{ mysql_host }}/{{ mysql_database }}"
    state: started
    restart_policy: always
  with_sequence: "start=1 end={{ container_num }}"

- name: Create CNAME for agama
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ nsupdate_key_secret }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}"
    record: "www-{{ inventory_hostname.split('-')[1] }}"
    type: "CNAME"
    value: "{{ inventory_hostname }}"
