{
 "title": "Backups",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Influxdb backups",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"manuniia\", type=\"full\", service=\"influxdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL backups",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backups_total{user=\"manuniia\", type=\"full\", service=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last_success_time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "backup_last_success_time{user=\"manuniia\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}