{
 "title": "Main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bind status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{job=\"bind9\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{job=\"nginx\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mysql status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{job=\"mysql\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Influxdb status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success{job=\"influxdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Haproxy status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_up{job=\"haproxy\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keepalived status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_up{job=\"keepalived\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_write_write_ok{job=\"influxdb\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Haproxy container vstatus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{job=\"haproxy\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "keepalived_vrrp_state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{job=\"keepalived\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}