- name: config prometheus.yml file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: Restart prometheus

- name: config prometheus default file
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/prometheus

- name: Start prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes

- name: Create CNAME for prometheus
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_secret: "{{ nsupdate_key_secret }}"
    key_algorithm: "hmac-sha256"
    server: "{{ hostvars[groups['dns_primary'][0]]['ansible_default_ipv4']['address'] }}"
    zone: "{{ startup_name }}"
    record: "prometheus"
    type: "CNAME"
    value: "{{ inventory_hostname }}"