- name: Restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Restart prometheus-mysqld-exporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: restarted

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname == mysql_host

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    primary_host: "{{ mysql_host }}"
    primary_user: "{{ mysql_rep_user }}"
    primary_password: "{{ mysql_rep_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname == mysql_host